Loading a dataset - Healthcare dataset

In [2]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
import pandas as pd
file_path = '/content/drive/MyDrive/Healthcare_Analysis_Dataset.csv'
df = pd.read_csv(file_path)

Mounted at /content/drive

Inspecting the dataset loaded

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient ID          55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
 15  Hospital Latitude   55500 non-null  float64
 16  Hospital Longitude  55500 non-null  float64
dtypes: float64(3), int64(2), object(12)
memory usage: 7.2+ MB

Look up the first few rows of the dataset

In [4]:
df.head()

,Patient ID,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Hospital Latitude,Hospital Longitude
0,ID-2621,64,Female,A+,Hypertension,3/3/2020,Jessica Marshall,Houston Methodist Hospital,Medicare,43913.98374,353,Elective,3/6/2020,Ibuprofen,Abnormal,29.709541,-95.398605
1,ID-2623,18,Female,A+,Hypertension,9/12/2022,Sean Jimenez,Houston Methodist Hospital,Medicare,21146.04893,457,Elective,9/29/2022,Ibuprofen,Abnormal,29.709541,-95.398605
2,ID-2624,57,Female,A+,Hypertension,2/26/2022,Jennifer Crawford,Houston Methodist Hospital,Medicare,47946.86128,200,Elective,3/25/2022,Ibuprofen,Abnormal,29.709541,-95.398605
3,ID-2634,77,Female,A+,Hypertension,12/11/2020,Tiffany Ramirez,Houston Methodist Hospital,Medicare,13385.07791,238,Elective,12/26/2020,Ibuprofen,Abnormal,29.709541,-95.398605
4,ID-2720,81,Female,A+,Hypertension,9/19/2019,Peter Roberts,Houston Methodist Hospital,Medicare,32984.89368,317,Elective,9/26/2019,Ibuprofen,Abnormal,29.709541,-95.398605

Identification of null values in the dataset

In [5]:
df.isnull().sum()

Patient ID            0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
Hospital Latitude     0
Hospital Longitude    0
dtype: int64

Handling Missing values (Imputation)
Check if Age is null, impute with Median value

In [6]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df.head()

,Patient ID,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Hospital Latitude,Hospital Longitude
0,ID-2621,64,Female,A+,Hypertension,3/3/2020,Jessica Marshall,Houston Methodist Hospital,Medicare,43913.98374,353,Elective,3/6/2020,Ibuprofen,Abnormal,29.709541,-95.398605
1,ID-2623,18,Female,A+,Hypertension,9/12/2022,Sean Jimenez,Houston Methodist Hospital,Medicare,21146.04893,457,Elective,9/29/2022,Ibuprofen,Abnormal,29.709541,-95.398605
2,ID-2624,57,Female,A+,Hypertension,2/26/2022,Jennifer Crawford,Houston Methodist Hospital,Medicare,47946.86128,200,Elective,3/25/2022,Ibuprofen,Abnormal,29.709541,-95.398605
3,ID-2634,77,Female,A+,Hypertension,12/11/2020,Tiffany Ramirez,Houston Methodist Hospital,Medicare,13385.07791,238,Elective,12/26/2020,Ibuprofen,Abnormal,29.709541,-95.398605
4,ID-2720,81,Female,A+,Hypertension,9/19/2019,Peter Roberts,Houston Methodist Hospital,Medicare,32984.89368,317,Elective,9/26/2019,Ibuprofen,Abnormal,29.709541,-95.398605

Datatype conversion - convert admission date to Datetime

In [6]:
df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient ID          55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  datetime64[ns]
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
 15  Hospital Latitude   55500 non-null  float64
 16  Hospital Longitude  55500 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(11)
memory usage: 7.2+ MB

Creation of a Derived column - Billing Category. Categorizing billing into 'High' or 'Low' for easier visualization

In [7]:
df['Billing_Category']= np.where(df['Billing Amount']>5000,'High','Low')
df.head()

,Patient ID,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,Hospital Latitude,Hospital Longitude,Billing_Category
0,ID-2621,64,Female,A+,Hypertension,2020-03-03,Jessica Marshall,Houston Methodist Hospital,Medicare,43913.98374,353,Elective,3/6/2020,Ibuprofen,Abnormal,29.709541,-95.398605,High
1,ID-2623,18,Female,A+,Hypertension,2022-09-12,Sean Jimenez,Houston Methodist Hospital,Medicare,21146.04893,457,Elective,9/29/2022,Ibuprofen,Abnormal,29.709541,-95.398605,High
2,ID-2624,57,Female,A+,Hypertension,2022-02-26,Jennifer Crawford,Houston Methodist Hospital,Medicare,47946.86128,200,Elective,3/25/2022,Ibuprofen,Abnormal,29.709541,-95.398605,High
3,ID-2634,77,Female,A+,Hypertension,2020-12-11,Tiffany Ramirez,Houston Methodist Hospital,Medicare,13385.07791,238,Elective,12/26/2020,Ibuprofen,Abnormal,29.709541,-95.398605,High
4,ID-2720,81,Female,A+,Hypertension,2019-09-19,Peter Roberts,Houston Methodist Hospital,Medicare,32984.89368,317,Elective,9/26/2019,Ibuprofen,Abnormal,29.709541,-95.398605,High

Export the cleaned dataset to csv

In [8]:
df.to_csv('Cleaned_Healthcare.csv',index=False)
print('Exported Successfully')

Exported Successfully

In [11]:
from google.colab import files
files.download('Cleaned_Healthcare.csv')